services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=ETC/UTC
    ports:
     - "8096:8096"
    volumes:
      - /path/to/jellyfin/config:/config
      - /path/to/tvseries:/tvshows
      - /path/to/movies:/movies
    restart: unless-stopped
