services:
#radarr
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /data/arr/radarr/config:/config
      - /data/arr/radarr/movies:/movies #optional
      - /data/arr/qbittorrent/downloads:/downloads #optional
    restart: unless-stopped

#Sonarr
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /data/arr/sonarr/config:/config
      - /data/arr/sonarr/tvseries:/tv #optional
      - /data/arr/qbittorrent/downloads:/downloads #optional
    restart: unless-stopped

#Prowlarr
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /data/arr/prowlarr/config:/config
    restart: unless-stopped

#qbittorrent
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /data/arr/qbittorrent/config:/config
      - /data/arr/qbittorrent/downloads:/downloads #optional
    restart: unless-stopped

#bazarr
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /data/arr/bazarr/config:/config
      - /data/arr/radarr/movies:/movies
      - /data/arr/sonarr/tvseries:/tv
    restart: unless-stopped

#jellyseerr
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=info
      - TZ=Etc/UTC
    volumes:
      - /data/arr/jellyseerr/config:/app/config
    restart: unless-stopped

#jellyfin 
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=ETC/UTC
#      - JELLYFIN-PublishedServerUrl=http://192.168.0.5
    ports:
     - "0.0.0.0:8096:8096"
    volumes:
      - /data/arr/jellyfin/config:/config
      - /data/arr/sonarr/tvseries:/tvshows
      - /data/arr/radarr/movies:/movies
    restart: unless-stopped

#plex
#  plex:
#    image: lscr.io/linuxserver/plex:latest
#    container_name: plex
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Etc/UTC
#      - PLEX_CLAIM=claim_besQF2Ld7y_V4f6agkq8
#    ports:
#      - 32400:32400
#    volumes:
#      - /data/arr/plex/config:/config
#      - /data/arr/sonarr/tvseries:/data/tvshows
#      - /data/arr/radarr/movies:/data/movies
#    restart: unless-stopped

#Gluetun
  gluetun:
    image: qmcgaw/gluetun
    ports:
      - 5055:5055 #jellyseerr 
      - 6767:6767 #bazarr
      - 8080:8080 #qbit
      - 6881:6881 #qbit
      - 6881:6881/udp #qbit
      - 7878:7878 #radarr
      - 8989:8989 #sonarr
      - 9696:9696 #prowlarr
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=4Jub5h3t8hooHZOVLbw8dC6iUnumBZiet06TeQKqEG0=
      - WIREGUARD_ADDRESSES=10.14.0.2/16
      - SERVER_COUNTRIES=United Kingdom
