service:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    ports:
      - 5055:5055
    environment:
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=info
      - TZ=Etc/UTC
    volumes:
      - /path/to/jellyseerr/config:/app/config
    restart: unless-stopped
